
export const countries = [
    { name: 'India', dial_code: '+91', code: 'IN', emoji: '🇮🇳' },
    { name: 'United States', dial_code: '+1', code: 'US', emoji: '🇺🇸' },
    { name: 'United Kingdom', dial_code: '+44', code: 'GB', emoji: '🇬🇧' },
    { name: 'Australia', dial_code: '+61', code: 'AU', emoji: '🇦🇺' },
    { name: 'Canada', dial_code: '+1', code: 'CA', emoji: '🇨🇦' },
    { name: 'Afghanistan', dial_code: '+93', code: 'AF', emoji: '🇦🇫' },
    { name: 'Albania', dial_code: '+355', code: 'AL', emoji: '🇦🇱' },
    { name: 'Algeria', dial_code: '+213', code: 'DZ', emoji: '🇩🇿' },
    { name: 'American Samoa', dial_code: '+1684', code: 'AS', emoji: '🇦🇸' },
    { name: 'Andorra', dial_code: '+376', code: 'AD', emoji: '🇦🇩' },
    { name: 'Angola', dial_code: '+244', code: 'AO', emoji: '🇦🇴' },
    { name: 'Anguilla', dial_code: '+1264', code: 'AI', emoji: '🇦🇮' },
    { name: 'Antarctica', dial_code: '+672', code: 'AQ', emoji: '🇦🇶' },
    { name: 'Argentina', dial_code: '+54', code: 'AR', emoji: '🇦🇷' },
    { name: 'Armenia', dial_code: '+374', code: 'AM', emoji: '🇦🇲' },
    { name: 'Aruba', dial_code: '+297', code: 'AW', emoji: '🇦🇼' },
    { name: 'Austria', dial_code: '+43', code: 'AT', emoji: '🇦🇹' },
    { name: 'Azerbaijan', dial_code: '+994', code: 'AZ', emoji: '🇦🇿' },
    { name: 'Bahamas', dial_code: '+1242', code: 'BS', emoji: '🇧🇸' },
    { name: 'Bahrain', dial_code: '+973', code: 'BH', emoji: '🇧🇭' },
    { name: 'Bangladesh', dial_code: '+880', code: 'BD', emoji: '🇧🇩' },
    { name: 'Barbados', dial_code: '+1246', code: 'BB', emoji: '🇧🇧' },
    { name: 'Belarus', dial_code: '+375', code: 'BY', emoji: '🇧🇾' },
    { name: 'Belgium', dial_code: '+32', code: 'BE', emoji: '🇧🇪' },
    { name: 'Belize', dial_code: '+501', code: 'BZ', emoji: '🇧🇿' },
    { name: 'Benin', dial_code: '+229', code: 'BJ', emoji: '🇧🇯' },
    { name: 'Bermuda', dial_code: '+1441', code: 'BM', emoji: '🇧🇲' },
    { name: 'Bhutan', dial_code: '+975', code: 'BT', emoji: '🇧🇹' },
    { name: 'Bolivia', dial_code: '+591', code: 'BO', emoji: '🇧🇴' },
    { name: 'Brazil', dial_code: '+55', code: 'BR', emoji: '🇧🇷' },
    { name: 'Brunei Darussalam', dial_code: '+673', code: 'BN', emoji: '🇧🇳' },
    { name: 'Bulgaria', dial_code: '+359', code: 'BG', emoji: '🇧🇬' },
    { name: 'Burkina Faso', dial_code: '+226', code: 'BF', emoji: '🇧🇫' },
    { name: 'Burundi', dial_code: '+257', code: 'BI', emoji: '🇧🇮' },
    { name: 'Cambodia', dial_code: '+855', code: 'KH', emoji: '🇰🇭' },
    { name: 'Cameroon', dial_code: '+237', code: 'CM', emoji: '🇨🇲' },
    { name: 'Cape Verde', dial_code: '+238', code: 'CV', emoji: '🇨🇻' },
    { name: 'Central African Republic', dial_code: '+236', code: 'CF', emoji: '🇨🇫' },
    { name: 'Chad', dial_code: '+235', code: 'TD', emoji: '🇹🇩' },
    { name: 'Chile', dial_code: '+56', code: 'CL', emoji: '🇨🇱' },
    { name: 'China', dial_code: '+86', code: 'CN', emoji: '🇨🇳' },
    { name: 'Colombia', dial_code: '+57', code: 'CO', emoji: '🇨🇴' },
    { name: 'Congo', dial_code: '+242', code: 'CG', emoji: '🇨🇬' },
    { name: 'Cook Islands', dial_code: '+682', code: 'CK', emoji: '🇨🇰' },
    { name: 'Costa Rica', dial_code: '+506', code: 'CR', emoji: '🇨🇷' },
    { name: 'Croatia', dial_code: '+385', code: 'HR', emoji: '🇭🇷' },
    { name: 'Cuba', dial_code: '+53', code: 'CU', emoji: '🇨🇺' },
    { name: 'Cyprus', dial_code: '+357', code: 'CY', emoji: '🇨🇾' },
    { name: 'Czech Republic', dial_code: '+420', code: 'CZ', emoji: '🇨🇿' },
    { name: 'Denmark', dial_code: '+45', code: 'DK', emoji: '🇩🇰' },
    { name: 'Djibouti', dial_code: '+253', code: 'DJ', emoji: '🇩🇯' },
    { name: 'Dominica', dial_code: '+1767', code: 'DM', emoji: '🇩🇲' },
    { name: 'Ecuador', dial_code: '+593', code: 'EC', emoji: '🇪🇨' },
    { name: 'Egypt', dial_code: '+20', code: 'EG', emoji: '🇪🇬' },
    { name: 'El Salvador', dial_code: '+503', code: 'SV', emoji: '🇸🇻' },
    { name: 'Estonia', dial_code: '+372', code: 'EE', emoji: '🇪🇪' },
    { name: 'Ethiopia', dial_code: '+251', code: 'ET', emoji: '🇪🇹' },
    { name: 'Fiji', dial_code: '+679', code: 'FJ', emoji: '🇫🇯' },
    { name: 'Finland', dial_code: '+358', code: 'FI', emoji: '🇫🇮' },
    { name: 'France', dial_code: '+33', code: 'FR', emoji: '🇫🇷' },
    { name: 'Gabon', dial_code: '+241', code: 'GA', emoji: '🇬🇦' },
    { name: 'Gambia', dial_code: '+220', code: 'GM', emoji: '🇬🇲' },
    { name: 'Georgia', dial_code: '+995', code: 'GE', emoji: '🇬🇪' },
    { name: 'Germany', dial_code: '+49', code: 'DE', emoji: '🇩🇪' },
    { name: 'Ghana', dial_code: '+233', code: 'GH', emoji: '🇬🇭' },
    { name: 'Greece', dial_code: '+30', code: 'GR', emoji: '🇬🇷' },
    { name: 'Greenland', dial_code: '+299', code: 'GL', emoji: '🇬🇱' },
    { name: 'Guatemala', dial_code: '+502', code: 'GT', emoji: '🇬🇹' },
    { name: 'Guinea', dial_code: '+224', code: 'GN', emoji: '🇬🇳' },
    { name: 'Guyana', dial_code: '+592', code: 'GY', emoji: '🇬🇾' },
    { name: 'Haiti', dial_code: '+509', code: 'HT', emoji: '🇭🇹' },
    { name: 'Honduras', dial_code: '+504', code: 'HN', emoji: '🇭🇳' },
    { name: 'Hong Kong', dial_code: '+852', code: 'HK', emoji: '🇭🇰' },
    { name: 'Hungary', dial_code: '+36', code: 'HU', emoji: '🇭🇺' },
    { name: 'Iceland', dial_code: '+354', code: 'IS', emoji: '🇮🇸' },
    { name: 'Indonesia', dial_code: '+62', code: 'ID', emoji: '🇮🇩' },
    { name: 'Iran', dial_code: '+98', code: 'IR', emoji: '🇮🇷' },
    { name: 'Iraq', dial_code: '+964', code: 'IQ', emoji: '🇮🇶' },
    { name: 'Ireland', dial_code: '+353', code: 'IE', emoji: '🇮🇪' },
    { name: 'Israel', dial_code: '+972', code: 'IL', emoji: '🇮🇱' },
    { name: 'Italy', dial_code: '+39', code: 'IT', emoji: '🇮🇹' },
    { name: 'Jamaica', dial_code: '+1876', code: 'JM', emoji: '🇯🇲' },
    { name: 'Japan', dial_code: '+81', code: 'JP', emoji: '🇯🇵' },
    { name: 'Jordan', dial_code: '+962', code: 'JO', emoji: '🇯🇴' },
    { name: 'Kazakhstan', dial_code: '+7', code: 'KZ', emoji: '🇰🇿' },
    { name: 'Kenya', dial_code: '+254', code: 'KE', emoji: '🇰🇪' },
    { name: 'Kuwait', dial_code: '+965', code: 'KW', emoji: '🇰🇼' },
    { name: 'Lebanon', dial_code: '+961', code: 'LB', emoji: '🇱🇧' },
    { name: 'Libya', dial_code: '+218', code: 'LY', emoji: '🇱🇾' },
    { name: 'Liechtenstein', dial_code: '+423', code: 'LI', emoji: '🇱🇮' },
    { name: 'Lithuania', dial_code: '+370', code: 'LT', emoji: '🇱🇹' },
    { name: 'Luxembourg', dial_code: '+352', code: 'LU', emoji: '🇱🇺' },
    { name: 'Malaysia', dial_code: '+60', code: 'MY', emoji: '🇲🇾' },
    { name: 'Maldives', dial_code: '+960', code: 'MV', emoji: '🇲🇻' },
    { name: 'Mali', dial_code: '+223', code: 'ML', emoji: '🇲🇱' },
    { name: 'Malta', dial_code: '+356', code: 'MT', emoji: '🇲🇹' },
    { name: 'Mexico', dial_code: '+52', code: 'MX', emoji: '🇲🇽' },
    { name: 'Monaco', dial_code: '+377', code: 'MC', emoji: '🇲🇨' },
    { name: 'Mongolia', dial_code: '+976', code: 'MN', emoji: '🇲🇳' },
    { name: 'Montenegro', dial_code: '+382', code: 'ME', emoji: '🇲🇪' },
    { name: 'Morocco', dial_code: '+212', code: 'MA', emoji: '🇲🇦' },
    { name: 'Mozambique', dial_code: '+258', code: 'MZ', emoji: '🇲🇿' },
    { name: 'Myanmar', dial_code: '+95', code: 'MM', emoji: '🇲🇲' },
    { name: 'Namibia', dial_code: '+264', code: 'NA', emoji: '🇳🇦' },
    { name: 'Nepal', dial_code: '+977', code: 'NP', emoji: '🇳🇵' },
    { name: 'Netherlands', dial_code: '+31', code: 'NL', emoji: '🇳🇱' },
    { name: 'New Zealand', dial_code: '+64', code: 'NZ', emoji: '🇳🇿' },
    { name: 'Nicaragua', dial_code: '+505', code: 'NI', emoji: '🇳🇮' },
    { name: 'Niger', dial_code: '+227', code: 'NE', emoji: '🇳🇪' },
    { name: 'Nigeria', dial_code: '+234', code: 'NG', emoji: '🇳🇬' },
    { name: 'North Korea', dial_code: '+850', code: 'KP', emoji: '🇰🇵' },
    { name: 'Norway', dial_code: '+47', code: 'NO', emoji: '🇳🇴' },
    { name: 'Oman', dial_code: '+968', code: 'OM', emoji: '🇴🇲' },
    { name: 'Pakistan', dial_code: '+92', code: 'PK', emoji: '🇵🇰' },
    { name: 'Palestine', dial_code: '+970', code: 'PS', emoji: '🇵🇸' },
    { name: 'Panama', dial_code: '+507', code: 'PA', emoji: '🇵🇦' },
    { name: 'Paraguay', dial_code: '+595', code: 'PY', emoji: '🇵🇾' },
    { name: 'Peru', dial_code: '+51', code: 'PE', emoji: '🇵🇪' },
    { name: 'Philippines', dial_code: '+63', code: 'PH', emoji: '🇵🇭' },
    { name: 'Poland', dial_code: '+48', code: 'PL', emoji: '🇵🇱' },
    { name: 'Portugal', dial_code: '+351', code: 'PT', emoji: '🇵🇹' },
    { name: 'Puerto Rico', dial_code: '+1939', code: 'PR', emoji: '🇵🇷' },
    { name: 'Qatar', dial_code: '+974', code: 'QA', emoji: '🇶🇦' },
    { name: 'Romania', dial_code: '+40', code: 'RO', emoji: '🇷🇴' },
    { name: 'Russia', dial_code: '+7', code: 'RU', emoji: '🇷🇺' },
    { name: 'Rwanda', dial_code: '+250', code: 'RW', emoji: '🇷🇼' },
    { name: 'Saudi Arabia', dial_code: '+966', code: 'SA', emoji: '🇸🇦' },
    { name: 'Senegal', dial_code: '+221', code: 'SN', emoji: '🇸🇳' },
    { name: 'Serbia', dial_code: '+381', code: 'RS', emoji: '🇷🇸' },
    { name: 'Singapore', dial_code: '+65', code: 'SG', emoji: '🇸🇬' },
    { name: 'Slovakia', dial_code: '+421', code: 'SK', emoji: '🇸🇰' },
    { name: 'Slovenia', dial_code: '+386', code: 'SI', emoji: '🇸🇮' },
    { name: 'Somalia', dial_code: '+252', code: 'SO', emoji: '🇸🇴' },
    { name: 'South Africa', dial_code: '+27', code: 'ZA', emoji: '🇿🇦' },
    { name: 'South Korea', dial_code: '+82', code: 'KR', emoji: '🇰🇷' },
    { name: 'Spain', dial_code: '+34', code: 'ES', emoji: '🇪🇸' },
    { name: 'Sri Lanka', dial_code: '+94', code: 'LK', emoji: '🇱🇰' },
    { name: 'Sudan', dial_code: '+249', code: 'SD', emoji: '🇸🇩' },
    { name: 'Sweden', dial_code: '+46', code: 'SE', emoji: '🇸🇪' },
    { name: 'Switzerland', dial_code: '+41', code: 'CH', emoji: '🇨🇭' },
    { name: 'Syria', dial_code: '+963', code: 'SY', emoji: '🇸🇾' },
    { name: 'Taiwan', dial_code: '+886', code: 'TW', emoji: '🇹🇼' },
    { name: 'Tanzania', dial_code: '+255', code: 'TZ', emoji: '🇹🇿' },
    { name: 'Thailand', dial_code: '+66', code: 'TH', emoji: '🇹🇭' },
    { name: 'Togo', dial_code: '+228', code: 'TG', emoji: '🇹🇬' },
    { name: 'Tunisia', dial_code: '+216', code: 'TN', emoji: '🇹🇳' },
    { name: 'Turkey', dial_code: '+90', code: 'TR', emoji: '🇹🇷' },
    { name: 'Uganda', dial_code: '+256', code: 'UG', emoji: '🇺🇬' },
    { name: 'Ukraine', dial_code: '+380', code: 'UA', emoji: '🇺🇦' },
    { name: 'United Arab Emirates', dial_code: '+971', code: 'AE', emoji: '🇦🇪' },
    { name: 'Uruguay', dial_code: '+598', code: 'UY', emoji: '🇺🇾' },
    { name: 'Uzbekistan', dial_code: '+998', code: 'UZ', emoji: '🇺🇿' },
    { name: 'Venezuela', dial_code: '+58', code: 'VE', emoji: '🇻🇪' },
    { name: 'Vietnam', dial_code: '+84', code: 'VN', emoji: '🇻🇳' },
    { name: 'Yemen', dial_code: '+967', code: 'YE', emoji: '🇾🇪' },
    { name: 'Zambia', dial_code: '+260', code: 'ZM', emoji: '🇿🇲' },
    { name: 'Zimbabwe', dial_code: '+263', code: 'ZW', emoji: '🇿🇼' },
];
